import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"

# --- Folders used by the pipeline (created by 01_setup_sample_data.py) ---
INBOX_DIR = DATA_DIR / "inbox"                    # free-text order emails (input to AI agent)
STRUCTURED_DIR = DATA_DIR / "structured_orders"   # AI agent output -> RPA input
ESCALATION_DIR = DATA_DIR / "escalations"         # ambiguous orders routed to a human
INVOICE_DIR = DATA_DIR / "invoices"               # invoices generated by the RPA bot
OUTBOX_DIR = DATA_DIR / "outbox"                  # simulated outgoing emails (.eml files)
LOG_DIR = BASE_DIR / "logs"

PRODUCTS_XLSX = DATA_DIR / "products.xlsx"        # product catalogue + stock + prices
CUSTOMERS_XLSX = DATA_DIR / "customers.xlsx"      # customer master data
ERP_XLSX = DATA_DIR / "erp_orders.xlsx"           # order/invoice ledger ("ERP system")

# --- Business rules (mirror the BPMN To-Be model) ---
DISCOUNT_APPROVAL_THRESHOLD = 10.0    # % discount above which manager approval is required
PAYMENT_TERM_DAYS = 30                # invoice due date = order date + 30 days
REMINDER_INTERVAL_DAYS = 7            # wait between reminders
MAX_AUTO_REMINDERS = 2                # after 2 reminders -> escalate to human collections
CONFIDENCE_THRESHOLD = 0.80           # AI agent: below this -> escalate to human review
VAT_RATE = 0.09                       # 9% VAT (Irish reduced rate for food, illustrative)

# --- LLM settings for the AI agent ---
# Set your key here or via the GEMINI_API_KEY environment variable.
# If the key is left as the placeholder, the agent automatically runs in
# MOCK mode (a deterministic offline parser) so the demo works end-to-end
# without any external API.
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "PASTE_YOUR_GEMINI_API_KEY_HERE")
GEMINI_MODEL = "gemini-2.5-flash"
MOCK_MODE = GEMINI_API_KEY == "PASTE_YOUR_GEMINI_API_KEY_HERE"

SMTP_ENABLED = False  # True + configure below to send real emails instead of .eml files
SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD = "smtp.example.com", 587, "", ""

def ensure_dirs():
    for d in (DATA_DIR, INBOX_DIR, STRUCTURED_DIR, ESCALATION_DIR,
              INVOICE_DIR, OUTBOX_DIR, LOG_DIR):
        d.mkdir(parents=True, exist_ok=True)
